### ISSUE TITLE
traceId and spanId missing in access logs 

### ISSUE THREAD

**Issue by oemergenc** [micrometer-metrics/tracing#600] opened 2024-02-19 20:34 UTC
I already opened an issue here:

https://github.com/micrometer-metrics/context-propagation/issues/212

Unfortunately nobody responded and I am really stuck with this one. Therefore I am trying my luck now here.

I am trying to set up a very simple spring cloud gateway application and I want to log traceIds and spanId. I was able to create a simple example which seems to work, although I am not sure wether I have configured context propagation the right way. Anyway, there is one test failing due to the fact that the traceId and spanId are missing from one request and I cannot understand why. Please have a look at this repo:

https://github.com/oemergenc/spring-cloud-gateway-upgrade

I have added a single integration test which is success for one request and fails for another and I have no idea why. The test is here:
https://github.com/oemergenc/spring-cloud-gateway-upgrade/blob/a79b683f7d6dd4194cdf21029c256471b550f915/src/test/java/com/gateway/ItTest.java#L13

Can anyone help me with that?

It would also be nice, if someone can check wether my configuration here:
https://github.com/oemergenc/spring-cloud-gateway-upgrade/blob/e3045ee2137d56b0fe0f7751409e48f39bce7f74/src/main/java/com/gateway/configuration/TracingConfiguration.java#L27
is correct to have working traceId and spanId propagation?

Thanks in advance.

**Comment by ilya40umov** [comment] 2024-02-19 21:25
Not really sure if it's a problem or not, but your [base test class](https://github.com/oemergenc/spring-cloud-gateway-upgrade/blob/main/src/test/java/com/gateway/AbstractTestBase.java) is using `@AutoConfigureObservability` annotation.
If I check the javadoc for this annotation: https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/autoconfigure/actuate/observability/AutoConfigureObservability.html, it states:

```
Annotation that can be applied to a test class to enable auto-configuration for observability.
If this annotation is applied to a sliced test, an in-memory MeterRegistry, a no-op Tracer and an ObservationRegistry is added to the application context.
```

I guess `a no-op Tracer` is likely not creating traces / spans as the proper implementation.

**Comment by oemergenc** [comment] 2024-02-20 07:36
Hi, 

thanks for your answer. I checked it and with the annotation being removed the test is still failing. If its still related to this annotation that the behavior ist still strange, since there is one test succeeding and one is failing.

**Comment by jonatan-ivanov** [comment] 2024-02-27 20:55
Duplicate of https://github.com/micrometer-metrics/context-propagation/issues/212

**Closed by jonatan-ivanov** 2024-02-27 20:55 UTC
