### ISSUE TITLE
ObservationAwareBaggageThreadLocalAccessor closes baggage scopes in wrong order

### ISSUE THREAD

**Issue by Antosch** [micrometer-metrics/tracing#607] opened 2024-02-25 18:24 UTC
Hey,

so i reported this issue last week but it was after my original issue was closed. I do not if you get any notifications on closed issues so i decided to post it here again. I point out the bug in my last comment of the original issue -> https://github.com/micrometer-metrics/tracing/issues/579#issuecomment-1961445681

**Comment by jonatan-ivanov** [comment] 2024-03-12 22:44
We do, you can comment on closed issues and discuss it further there, we can also reopen issues as needed.

Duplicate of https://github.com/micrometer-metrics/tracing/issues/579

**Closed by jonatan-ivanov** 2024-03-12 22:44 UTC
