### ISSUE TITLE
Not able to access trace from within ErrorWebExceptionHandler

### ISSUE THREAD

**Issue by chechoochoo** [micrometer-metrics/tracing#269] opened 2023-05-28 20:41 UTC
Using:
- io.micrometer#micrometer-core;1.10.6
- io.micrometer#micrometer-tracing;1.0.4
- io.micrometer#micrometer-tracing-bridge-otel;1.0.4

and
- spring-boot-starter-webflux:3.0.6

The trace is not accessible neither within `DefaultErrorWebExceptionHandler` nor in custom handler that implements `ErrorWebExceptionHandler`;

note - I enabled `Hooks.enableAutomaticContextPropagation();` in may application class

**Comment by shakuzen** [comment] 2023-05-29 03:20
This sounds like a duplicate of https://github.com/spring-projects/spring-boot/issues/35604 / https://github.com/spring-projects/spring-framework/issues/30013.

**Closed** 2023-07-21 08:39 UTC
