### ISSUE TITLE
Baggage support in Observation

### ISSUE THREAD

**Issue by ttddyy** [micrometer-metrics/tracing#563] opened 2024-01-30 20:59 UTC
Currently, there is no direct association between `Observation` and `Baggage`.
If I want to use baggage, I need to interact with Tracer API. Then, the code needs to mix observation and tracing, which I feel reduces the value of the observation abstraction.

How about tracing-observation-handler to have a list of observation tags that will be converted to baggage?

For example, 
```java
Set<String> baggageTags = Set.of("foo.id");
DefaultTracingObservationHandler handler = new DefaultTracingObservationHandler(tracer, baggageTags);
...
```

When `Observation` has `foo.id` tag, it will be treated as baggage.

It would be nice to integrate `Observation` and `Baggage` to eliminate the Tracer API usage in user code for baggage.

**Comment by ilya40umov** [comment] 2024-02-15 17:13
👍 Asked about it in https://github.com/micrometer-metrics/tracing/issues/455, so I wonder I this issue would render my question answered. Wdyt?

**Comment by marcingrzejszczak** [comment] 2024-05-06 09:49
duplicate of https://github.com/micrometer-metrics/tracing/issues/455

BTW I really like what @ttddyy suggested. That the fact that a key-value is baggage would become an implementation detail of tracing.

**Closed by marcingrzejszczak** 2024-05-06 09:49 UTC
