### ISSUE TITLE
Issue propagating baggage

### ISSUE THREAD

**Issue by toonborgers** [micrometer-metrics/tracing#320] opened 2023-08-08 11:54 UTC
In our apps, we use kafka for async communication. We have some code set up to also pass along tracing info in the kafka headers. With trying to upgrade to spring boot 3.1, this started failing. 

In the old, working version we have following micrometer libraries:

```
io.micrometer:context-propagation:1.0.4
io.micrometer:micrometer-commons:1.10.9
io.micrometer:micrometer-core:1.10.9
io.micrometer:micrometer-observation:1.10.9
io.micrometer:micrometer-tracing:1.0.8
io.micrometer:micrometer-tracing-bridge-otel:1.0.8
```

After upgrading, this became
```
io.micrometer:context-propagation:1.0.4
io.micrometer:micrometer-commons:1.11.2
io.micrometer:micrometer-core:1.11.2
io.micrometer:micrometer-observation:1.11.2
io.micrometer:micrometer-tracing:1.1.3
io.micrometer:micrometer-tracing-bridge-otel:1.1.3
```

What we're now noticing is that the info is no longer properly propagated. I created a small [sample project](https://github.com/toonborgers/baggage-issue) to show the issue.

There's a [test](https://github.com/toonborgers/baggage-issue/blob/boot-3.0/src/test/java/com/example/demo/DemoTest.java) which triggers the problem. We set some values as baggage (see [these lines](https://github.com/toonborgers/baggage-issue/blob/boot-3.0/src/test/java/com/example/demo/DemoTest.java#L78-L87) ). And then there's code in the kafka producer to take the tracing info and send it as kafka headers (see [these lines](https://github.com/toonborgers/baggage-issue/blob/boot-3.0/src/main/java/com/example/demo/TracingProducer.java#L94-L102) ).

Under the spring boot 3.0 versions of the libraries, this all works fine.

When switching to the boot 3.1 versions, however, it stops working. It seems that only the latest item gets added to the baggage (I can see this because the [logging in the producer](https://github.com/toonborgers/baggage-issue/blob/boot-3.1/src/main/java/com/example/demo/TracingProducer.java#L101) only logs the last one). I also used `createBaggageInScope` instead of `createBaggage` as advised by the deprecation warning.

Is there anything we're missing here?

**Comment by toonborgers** [comment] 2023-08-18 07:26
Looks like a duplicate of https://github.com/micrometer-metrics/tracing/pull/317

**Comment by marcingrzejszczak** [comment] 2023-08-18 11:45
Duplicate of #317

**Closed** 2023-08-18 11:45 UTC
